Implemented integration with apache kafka
lucasMatheusNunes/OpEvents pull request #6
Opened 2019-06-07 19:37 UTC by lucasNunes75

2019-06-14 19:12 UTC, sandokandias requested changes

2019-06-14 19:12 UTC, sandokandias commented on src/main/kotlin/br/com/zup/op/events/application/EventManager.kt
> +    fun reasonList(): ArrayList<ReasonEntity>
listReasons(): List<ReasonEntity>

2019-06-14 19:12 UTC, sandokandias commented on src/main/kotlin/br/com/zup/op/events/application/EventManager.kt
> +    fun listTopics(): ArrayList<TopicEntiy>
: List

2019-06-14 19:12 UTC, sandokandias commented on src/main/kotlin/br/com/zup/op/events/application/KafkaEventManager.kt
> +        var idEvent = ""
remove

2019-06-14 19:12 UTC, sandokandias commented on src/main/kotlin/br/com/zup/op/events/application/KafkaEventManager.kt
> +        val reasons = reasonRepository.findAll()
change to `this.listReasons()`

2019-06-19 20:57 UTC, thiagoaag commented on src/main/kotlin/br/com/zup/op/events/interfaces/controller/RepublishController.kt
> +@CrossOrigin(origins = ["http://localhost:3000", "http://localhost"]) // Enabling CORS only for the local application. We will be changing the address as soon as it is implemented for production.
Remove this

2019-06-19 20:57 UTC, thiagoaag commented on src/main/resources/db/migration/structure/V1__init.sql
> +CREATE TABLE event (
Rename file to -> V1.0__init.sql

2019-06-20 13:25 UTC, merged